require("dotenv").config();
const mongoose = require("mongoose");
const Post = require("./models/model.post");

const uniqueCaptionList = [
  "Breathtaking view from today's mountain hike! 🏞️✨",
  "Late night coding sessions & fresh coffee ☕💻",
  "Unforgettable weekend vibes with my favorite people 🎉",
  "Delicious homemade pizza makes every evening better 🍕🔥",
  "Chasing endless golden hour sunsets 🌅🧡",
  "Exploring hidden alleyways and vintage cafes in the city 🏙️🚶‍♂️",
  "Nature never fails to take my breath away 🌲🍃",
  "Stay curious, stay creative, and keep building 🚀",
  "Cozy Sunday morning reading with a warm cup of tea 📖☕",
  "Living in the moment and catching good memories ✨📸",
  "Golden hour hits different when you're by the beach 🌄🌊",
  "Work hard in silence, let your progress make the noise 💪💯",
  "Finding joy in the simple, quiet pleasures of life 🌻",
  "Never stop exploring new horizons and fresh perspectives 🗺️✨",
  "Good times, warm sunshine, and ocean waves 🏖️☀️",
  "Freshly brewed espresso to kickstart a productive week ☕⚡",
  "Architecture that speaks to the soul 🏛️💫",
  "A quiet walk in the forest is all the therapy I need 🍃🍂",
  "Tasting authentic street food in the heart of downtown 🌮😋",
  "Milestones achieved, on to the next big challenge! 🎯🏆",
  "The beauty of autumn colors in full bloom 🍁🍁",
  "Distant mountain tops covered in fresh snow 🏔️❄️",
  "Art is not what you see, but what you make others see 🎨🖌️",
  "Late night city lights and rainy street reflections 🌧️🌃",
  "Sweat now, shine later! Morning workout completed 🏋️‍♂️🔥",
  "Fresh bakery treats to sweeten the day 🥐🍰",
  "Surrounding myself with good energy and positive vibes ✨🌿",
  "Stargazing under a crystal clear night sky 🌌⭐",
  "Every sunset brings the promise of a new dawn 🌄",
  "A quick weekend getaway to recharge the mind 🚗💨",
  "Minimalist aesthetics & clean design inspiration 📐📱",
  "Fresh smoothie bowl to start the morning right 🍓🥣",
  "Road trips and endless playlists 🎵🛣️",
  "Capturing candid moments that last forever 📷🤍",
  "Morning mist over the peaceful lake 🌫️⛵",
  "Chasing dreams and making them reality 💫🌟",
  "The aroma of fresh coffee in the early morning ☕☀️",
  "Exploring coastal trails with a sea breeze 🌊🌊",
  "Creative process in action - turning ideas into code 💻🔮",
  "Warm bonfire nights under the stars 🪵🔥",
  "Tacos & sunshine make the ultimate combo 🌮☀️",
  "Feast for the eyes and the stomach 🍲✨",
  "Fitness journey progress - consistency is key 💪📊",
  "Wandering through ancient cobblestone streets 🏰🌾",
  "Sun-kissed mornings & gentle ocean breezes 🌅🌴",
  "A bowl of hot ramen on a chilly evening 🍜❄️",
  "Dreaming big, working focused, staying humble 🚀✨",
  "Unwinding with a great book after a busy day 📚🛋️",
  "Nature's canvas is filled with vibrant colors 🎨🌸",
  "Finding peace away from the urban noise 🌿🏞️",
  "Freshly picked flowers adding color to the room 🌸🌷",
  "Savoring every bite of this gourmet pasta 🍝🍷",
  "Reflecting on the journey so far with gratitude 🙏✨",
  "Early morning runs while the city is still asleep 🏃‍♂️🌅",
  "Desk setup upgrade complete! Time to crush goals 🖥️⚡",
  "Weekend market finds and handmade crafts 🛍️✨",
  "A peaceful paddle across calm waters 🚣‍♂️🌊",
  "Basking in the golden rays of late afternoon 🌄🌾",
  "Creating memories that will last a lifetime 🤍📸",
  "Sweet indulgence - chocolate lava cake 🍫🍨",
  "Chasing waterfalls deep inside the rain forest 🌊🌴",
  "Urban exploration & street photography session 📸🌆",
  "Small daily habits create big long-term wins 🌱📈",
  "Tropical paradise & crystal blue lagoons 🏝️🌺",
  "Hot chocolate & thick blankets on rainy days ☕🌧️",
  "Freshly baked sourdough bread out of the oven 🍞🥖",
  "Sunset views from high up on the rooftop terrace 🌅🏢",
  "Keeping things simple, clean, and elegant ✨🤍",
  "Adventures are the best way to learn 🎒🗺️",
  "A hearty brunch to start a lazy weekend 🥑🍳",
  "Concert night - energy was absolutely unreal! 🎸⚡",
  "Morning light filtering through the window blinds ☀️🪟",
  "Patience, persistence, and passion 💪🚀",
  "A serene walk through botanical gardens 🌿🌺",
  "Crisp autumn air and falling leaves 🍂🍁",
  "Juicy burgers and crispy fries for cheat day 🍔🍟",
  "Deep focus mode engaged 🧠💻",
  "Watching the ocean waves crash against the cliffs 🌊⛰️",
  "Cozy aesthetic with fairy lights and warm tea 🫖✨",
  "Life is better when you're laughing 😃🤍",
  "The quiet magic of early dawn 🌌🌅",
  "Tasting artisanal coffee from local roasters ☕🌱",
  "Camping under a sky full of bright constellations ⛺⭐",
  "Brightening up the space with green houseplants 🪴🌾",
  "Chilling by the pool with an iced drink 🍹🏊‍♂️",
  "Mastering new skills every single day 📚💡",
  "A scenic drive along the winding coastline 🛣️🌊",
  "Homemade sushi night with family 🍣🥢",
  "Golden hour glow hit just right 🌄✨",
  "Capturing the beauty in everyday moments 📸🍃",
  "Nothing beats a homemade Sunday roast 🍖🍷",
  "Finding calm amid the busy bustle 🧘‍♂️🕊️",
  "Crisp mountain air & pine trees all around 🌲🏔️",
  "Exploring local art galleries & exhibitions 🎨🖼️",
  "Fresh berry tart dessert 🫐🥧",
  "Pushing past limits and breaking barriers 💥💪",
  "A peaceful afternoon strolling by the harbor ⛵🏙️",
  "Watching rain drops race down the glass window 🌧️🪟",
  "Healthy green smoothie for a boost of energy 🥑🥤",
  "Surrounded by nature's quiet tranquility 🌿🕊️",
  "Sunsets are proof that endings can be beautiful too 🌅💫",
  "Late night brainstorms & whiteboards 🧠✏️",
  "A cozy fireside evening with friends 🪵🔥",
  "Savoring authentic wood-fired pizza 🍕🇮🇹",
  "Focus on progress, not perfection 🌱📈",
  "Stunning valley view from the cliff edge ⛰️🦅",
  "Freshly popped popcorn & movie night 🍿🎬",
  "Walking along the shore as the tide comes in 🌊🏖️",
  "Clean code, clean architecture, happy dev 💻✨",
  "Pastel skies during dusk 🌇💖",
  "Weekend brunch with bottomless mimosas 🥂🍳",
  "Exploring historic monuments & landmarks 🏛️🗺️",
  "Fresh avocado toast sprinkled with chili flakes 🥑🍞",
  "Biking through scenic countryside trails 🚴‍♂️🌾",
  "Capturing the contrast between shadows and light 📸🌓",
  "A warm hug in a cup - hot matcha latte 🍵💚",
  "Sunset colors reflecting on quiet lake waters 🌅🛶",
  "Building the future line by line 🚀💻",
  "Tasting exotic fruits at the vibrant night market 🍍🍉",
  "Winter wonderland & snow-capped pines ❄️🌲",
  "Finding magic in the mundane moments ✨🌿",
  "Freshly squeezed orange juice in the morning 🍊🥛",
  "Hiking to the highest peak for this view 🏔️🏆",
  "Smooth Jazz and a quiet evening vibe 🎷🍷",
  "The thrill of discovering a new favorite spot 📍✨",
  "Delicious berry pancakes with maple syrup 🥞🍯",
  "Consistency today leads to success tomorrow 🎯💪",
  "A tranquil sanctuary surrounded by bamboo 🎋🕊️",
  "Golden afternoon sun beaming through leaves ☀️🍃",
  "A slice of decadent red velvet cake 🍰❤️",
  "Night skyline viewed from the top of the tower 🏙️🌟",
  "Every day is a fresh new canvas 🎨🌤️",
  "Fresh garden salad with balsamic glaze 🥗🥑",
  "Chasing horizons and crossing oceans ✈️🌊",
  "A cup of hot chai on a rainy afternoon ☕🌧️",
  "Quiet reflection beside the flowing river 🌊🍃",
  "Tasting homemade gelato on a warm summer day 🍨☀️",
  "Sticking to the grind until goals are achieved 💯🚀",
  "A sea of wild sunflowers stretching to the horizon 🌻☀️",
  "Capturing urban vibes and city architecture 📸🏙️",
  "Freshly grilled seafood by the pier 🦐🦀",
  "Surround yourself with inspirations and positive energy 💫✨",
  "Sunset hues fading into a starry twilight 🌅🌌",
  "Morning yoga and meditation by the beach 🧘‍♀️🌊",
  "Crisp waffles topped with fresh strawberries & cream 🧇🍓",
  "Code, test, deploy, repeat! 🚀💻",
  "Wandering through a fragrant lavender field 🪻💜",
  "A cozy reading nook bathed in warm sunlight 📚☀️",
  "Feast of flavors - tapas and sangria 🥘🍷",
  "Embracing every step of the journey 🚶‍♂️✨",
  "Distant thunder and cool summer rain ⛈️🌧️",
  "Freshly blended acai bowl with granola 🫐🥣",
  "Exploring hidden waterfalls in the wilderness 🌊⛰️",
  "Minimalist workstation setup for maximum focus 🖥️✨",
  "The gentle murmur of stream waters in the woods 🌊🌲",
  "A slice of warm apple pie with vanilla ice cream 🥧🍨",
  "Dreaming under a sky full of shooting stars 🌌💫",
  "Early morning fog lifting off the meadow 🌫️🌾",
  "Tasting hand-crafted artisan chocolates 🍫✨",
  "Pushing forward no matter the obstacles 🚀💪",
  "Strolling through vibrant autumn orchards 🍎🍂",
  "Golden hour backlight hitting the grass 🌾🌅",
  "A hot bowl of pho on a chilly winter afternoon 🍜❄️",
  "Simple living, high thinking 🕊️✨",
  "Watching boats dock at sunset in the harbor ⛵🌇",
  "Freshly brewed filter coffee to start the day ☕⚡",
  "Capturing geometry and symmetry in modern architecture 📸🏢",
  "A bowl of fresh summer cherries 🍒☀️",
  "Finding harmony in nature's rhythms 🌿🍃",
  "Late night coding session triumphs! 🏆💻",
  "Chasing reflections in quiet water puddles 🌧️✨",
  "Decadent cheesecake with raspberry drizzle 🍰🍇",
  "Surrounding myself with nature's serenity 🌲🕊️",
  "Sunset over desert dunes 🏜️🌅",
  "Morning stretches and fresh air 🌅🧘‍♂️",
  "Freshly baked cinnamon rolls fresh out of the oven 🌀🧈",
  "Building scalable solutions for tomorrow 🚀🌐",
  "Wandering through ancient forest glades 🌳🍃",
  "A cozy blanket, hot chocolate, and a good film ☕🎬",
  "Savoring grilled steak with garlic butter 🥩🧈",
  "Every small step brings you closer to the peak 🏔️🎯",
  "Watching waves roll onto golden sand 🌊🏖️",
  "Warm rays of sunlight breaking through clouds 🌤️✨",
  "Freshly made iced caramel macchiato 🧊☕",
  "Discovering hidden gems in neighboring towns 🏘️🗺️",
  "Capturing true smiles and spontaneous moments 📸😃",
  "A plate of crispy churros dipped in warm chocolate 🥖🍫",
  "Peace of mind is the greatest luxury 🕊️🤍",
  "Skyline glowing under twilight purple hues 🌇💜",
  "Freshly picked peaches from the orchard 🍑☀️",
  "Overcoming challenges one milestone at a time 💪🎯",
  "Walking along country roads lined with wildflowers 🌾🌸",
  "A steaming pot of herbal tea on a cold day 🫖❄️",
  "Tasting authentic Italian gelato in a waffle cone 🍦🇮🇹",
  "Let your energy attract your tribe ✨🤍",
  "Reflections of city skyscrapers on glass facades 🏢🪟",
  "Fresh blueberry muffins straight from the kitchen 🫐🧁",
  "Coding passion turned into working reality 💻🚀",
  "Watching the full moon rise over ocean horizon 🌕🌊",
  "A morning stroll through misty pine woods 🌫️🌲",
  "Creamy mushroom risotto topped with parmesan 🍚🧀",
  "Embrace the beauty of the present moment ✨🕊️",
  "Golden wheat fields swaying gently in the wind 🌾💨",
  "Capturing shadows and highlights in urban street photography 📸🌆",
  "Freshly squeezed lemonade on a hot afternoon 🍋🧊",
  "Setting big targets and taking relentless action 🎯💪",
  "A peaceful Zen garden with smooth stones & moss 🪨🌱",
  "Sunset gradients painted across the horizon 🌅🎨",
  "Delicious churros with dulce de leche 🥖🍯",
  "Gratitude transforms everyday moments into joy 🙏✨",
  "A quiet boat ride along tranquil canals 🚣‍♂️🏞️",
  "Fresh espresso shot with a thick golden crema ☕⚡",
  "Innovating, creating, and pushing boundaries 🚀💡",
  "Snow-capped mountain peaks piercing cloud cover 🏔️☁️",
  "A plate of fresh dim sum dumplings 🥟🥢",
  "Surrounded by pages of old books in an ancient library 📚🏛️",
  "Capturing the magic of golden hour light 📸🌄",
  "Sweet Belgian waffles loaded with berries & honey 🧇🫐",
  "Consistency beats intensity every single time 📈💪",
  "A serene Japanese tea ceremony experience 🍵🌸",
  "Pink and orange clouds at dusk 🌇💖",
  "Savoring a bowl of spicy Thai curry 🍲🔥",
  "Focus on what truly matters in life 🕊️✨",
  "Wandering through cobblestone alleys filled with ivy 🌿🏰",
  "Freshly blended mango passionfruit smoothie 🥭🥤",
  "Turning complex problems into simple code 💻🧠",
  "Sunset reflections on wet sea sand 🌅🌊",
  "Cozy knit sweaters and warm pumpkin spice 🎃☕",
  "Tasting authentic wood-fired Margherita pizza 🍕🌿",
  "Believe in the power of small daily progress 🌱🎯",
  "A peaceful stroll along the riverbank at sunset 🌊🌇",
  "Freshly baked croissant & café au lait 🥐☕",
  "Capturing life as it happens 📸✨",
  "Juicy grilled skewers at the night bazaar 🍢🔥",
  "Keep your face toward the sunshine and shadows fall behind ☀️🕊️",
  "Misty mountain ridge at break of dawn 🌫️⛰️",
  "Fresh strawberry shortcake dessert 🍰🍓",
  "Coding late, building fast, shipping daily 🚀💻",
  "Listening to rain on a tin roof while cozy indoors 🌧️🏠",
  "Golden hour glow on ancient stone walls 🏛️🌅",
  "Savoring a cup of single-origin pour-over coffee ☕🌱",
  "Finding beauty in simplicity 🤍✨",
  "Walking through a forest illuminated by sunbeams 🌲☀️",
  "Crisp tacos with fresh salsa and guac 🌮🥑",
  "Every line of code is a step toward the vision 💻🎯",
  "Sunset colors melting into evening dark 🌅🌌",
  "A warm bowl of clam chowder in a sourdough bowl 🍲🥖",
  "Creating timeless art with light and shadows 📸🎨",
  "Quiet mornings before the world wakes up ☀️🕊️",
  "Freshly picked apples from the family orchard 🍎🌳",
  "Savoring a hot cup of dark roast espresso ☕🖤",
  "Chasing adventure wherever the path leads 🎒🌄",
  "A colorful sunset over coastal cliffs 🌅⛰️",
  "Tasting gourmet tapas at a bustling sidewalk bar 🍷🥘",
  "Stay persistent, stay humble, stay hungry 🚀💪",
  "Walking through a canopy of green maple leaves 🌳🍃",
  "Freshly baked banana bread with walnuts 🍌🍞",
  "Capturing genuine laughter & unscripted moments 📸😃",
  "A bowl of warm oatmeal topped with nuts and honey 🥣🍯",
  "Surrounded by peaceful wilderness and open skies 🌾🦅",
  "Sunset glow illuminating the city skyline 🌇🏢",
  "Savoring authentic French macarons 🍬🇫🇷",
  "Code with purpose, build with passion 💻⚡",
  "A quiet evening spent stargazing on the porch 🌌✨",
  "Freshly squeezed grapefruit juice 🍊🍹",
  "Finding inspiration in unexpected places 💡✨",
  "Crisp morning air and distant mountain views 🏔️🌅",
  "Delicious wood-fired garlic bread 🥖🧄",
  "Every accomplishment starts with the decision to try 🎯💪",
  "Watching sea waves lap gently against rocky shore 🌊🪨",
  "Freshly brewed iced black tea with lemon 🧊☕",
  "Capturing architectural details and textures 📸🏛️",
  "A bowl of fresh wild blackberries 🫐🍃",
  "Peace, quiet, and a good cup of coffee ☕🕊️",
  "Sunset reflections in a calm infinity pool 🌅🏊‍♂️",
  "Savoring authentic Mexican street tacos 🌮🇲🇽",
  "Building dreams into tangible reality 🚀✨",
  "Walking through a path of fallen golden leaves 🍂🍁",
  "Freshly baked chocolate chip cookies out of the oven 🍪🥛",
  "Capturing the vibrant energy of the city 📸🌆",
  "A cozy fireside mug of mulled cider ☕🍎",
  "Surrounding myself with growth and positivity 🌱✨",
  "Sunset views over rolling vineyard hills 🍇🌅",
  "Delicious creamy carbonara pasta 🍝🧀",
  "Hard work & dedication will always pay off 💯💪",
  "A quiet walk along a deserted beach at sunrise 🌅🏖️",
  "Freshly roasted coffee beans aroma ☕🌱",
  "Capturing light reflections on glass buildings 📸🏢",
  "A plate of fresh Greek salad with feta & olives 🥗🧀",
  "Living life with purpose, gratitude, and joy ✨🕊️",
  "Sunset clouds painted in shades of violet 🌇💜",
  "Savoring a warm slice of pecan pie 🥧🍯",
  "Code, innovate, iterate, and succeed 🚀💻",
  "Walking through misty pine trails in early morning 🌫️🌲",
  "Freshly squeezed watermelon juice on a hot day 🍉🧊",
  "Capturing honest emotion through the lens 📸🤍",
  "A bowl of hot chicken noodle soup on a cold evening 🍲❄️",
  "Surrounded by mountain peaks and endless skies 🏔️🦅",
  "Sunset horizon over calm ocean waters 🌅🌊",
  "Savoring authentic Belgian chocolate truffles 🍫🇧🇪",
  "Focus, dedication, and daily execution 🎯💪",
  "Walking under a canopy of pink cherry blossoms 🌸🌸",
  "Freshly baked blueberry scones 🫐🧁",
  "Capturing golden light dancing through trees 📸🌳",
  "A hot cup of spiced chai on a rainy evening 🫖🌧️",
  "Finding tranquility in nature's quiet spaces 🌿🕊️",
  "Sunset hues reflecting off snowy slopes 🌅❄️",
  "Savoring a plate of fresh seafood paella 🥘🦐",
  "Turning ideas into impactful software 💻🚀",
  "Walking through historic cobblestone squares at dusk 🌇🏰",
  "Freshly squeezed pineapple juice 🍍🍹",
  "Capturing atmospheric urban night scenes 📸🌃",
  "A bowl of warm lentil soup with crusty bread 🍲🥖",
  "Surrounded by peaceful meadows and wildflowers 🌾🌼",
  "Sunset colors over a peaceful lakeside cabin 🌅🏠",
  "Savoring authentic Italian Tiramisu 🍰🇮🇹",
  "Build with passion, lead with purpose 🚀✨",
  "Walking along coastal cliffs as twilight falls 🌇⛰️",
  "Freshly brewed iced matcha latte 🍵🧊",
  "Capturing candid moments of pure happiness 📸😊",
  "A hot bowl of miso soup to start dinner 🥣🥢",
  "Finding beauty in every single day 🕊️✨",
  "Sunset reflections on serene river waters 🌅🌊",
  "Savoring freshly baked almond croissants 🥐🌰",
  "Relentless effort produces outstanding results 🎯💯",
  "Walking through autumn woods as leaves drift down 🍂🍁",
  "Freshly blended kiwi & apple juice 🥝🧃",
  "Capturing architectural lines and geometric forms 📸📐",
  "A warm plate of cinnamon pancakes 🥞🍯",
  "Surrounded by good vibes and great company ✨🤍",
  "Sunset over city rooftops in purple and pink 🌇💖",
  "Savoring authentic Mexican churros with hot chocolate 🥖🍫",
  "Keep building, keep growing, keep shining 🚀🌟"
];

async function updateCaptions() {
  try {
    const mongoUri = process.env.MONGODB_URI || "mongodb://localhost:27017/L";
    console.log(`Connecting to MongoDB at ${mongoUri}...`);
    await mongoose.connect(mongoUri);

    console.log("Connected to MongoDB.");

    const posts = await Post.find({}).sort({ createdAt: -1 });
    console.log(`Found ${posts.length} total posts in database.`);

    if (posts.length === 0) {
      console.log("No posts found to update.");
      return;
    }

    let updatedCount = 0;
    const usedCaptions = new Set();

    for (let i = 0; i < posts.length; i++) {
      const post = posts[i];
      
      // Get unique caption
      let caption = uniqueCaptionList[i % uniqueCaptionList.length];
      
      // If we run out of static captions, append a unique suffix
      if (usedCaptions.has(caption)) {
        caption = `${caption} (#${i + 1})`;
      }

      usedCaptions.add(caption);
      post.caption = caption;
      await post.save();
      updatedCount++;
    }

    console.log(`\nSuccessfully updated ${updatedCount} posts in MongoDB!`);
    console.log(`All ${usedCaptions.size} posts now have UNIQUE captions.`);
    console.log("--------------------------------------------------\n");

  } catch (error) {
    console.error("Error updating post captions:", error);
  } finally {
    await mongoose.disconnect();
    console.log("MongoDB disconnected. Done!");
    process.exit(0);
  }
}

updateCaptions();
